spring.data.mongodb.uri=mongodb+srv://mucyoprinc12:<db_password>@cluster0.b7pzznr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/rehoboth
spring.data.mongodb.database=rehoboth


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
